[tools]
node = "latest"
hugo-extended = { version = "latest", postinstall = "hugo completion zsh > /usr/local/share/zsh/site-functions/_hugo" }

[tasks.server]
description = "Run development server"
run = "hugo server"
alias = 's'

[hooks]
postinstall = [
	"git submodule update --init"
]
